#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_DISK                         102
#define IDI_ICON_16PLUS_BANK                    109
#define IDI_ICON_16PLUS_OS                      110
#define IDI_ICON_ASR_BANK                       111
#define IDI_ICON_ASR_OS                         112
#define IDI_ICON_EPS_INST                       113
#define IDI_ICON_EPS_OS                         114
#define IDI_ICON_FOLDER                         116
#define IDI_ICON_INFO                           118
#define IDI_ICON_UNKNOWN                        120
#define IDI_ICON_EPS_BANK                       122
#define IDI_ICON_16PLUS_SEQ                     129
#define IDI_ICON_16PLUS_SONG                    131
#define IDI_ICON_ASR_SEQ                        132
#define IDI_ICON_ASR_SONG                       133
#define IDI_ICON_EPS_SEQ                        134
#define IDI_ICON_EPS_SONG                       135
#define IDI_ICON_16PLUS_FX                      141
#define IDI_ICON_ASR_FX                         142
#define IDI_ICON_EPS_MACRO                      143
#define IDI_ICON_ASR_MACRO                      144
#define IDI_ICON_ASR_ATRACK                     146
#define IDI_ICON_WAV                            148
#define IDI_ICON_CMD                            150
#define IDD_DLG_PROGRESS                        1000
#define IDC_STATIC_STATUS                       1001
#define IDC_GRP1                                1002
#define IDC_COMBO_DISK                          1003
#define IDC_GRP2                                1003
#define IDC_PGB                                 1004
#define IDC_BTN_DISK_CANCEL                     1006
#define IDD_DLG_OPTIONS                         1100
#define IDC_CBO_FILES                           1101
#define IDC_GRP3                                1102
#define IDC_GRP4                                1103
#define IDC_BTN_OK                              1104
#define IDC_BTN_MOUNT                           1105
#define IDC_BTN_UNMOUNT                         1106
#define IDC_CHK_FLOPPY                          1107
#define IDC_CHK_CDROM                           1108
#define IDC_CHK_PHYSICAL                        1109
#define IDC_CHK_IMAGE                           1110
#define IDC_CHK_RESCAN                          1111
#define IDC_BTN_CANCEL                          1112
#define IDC_CHK_LOGGING                         1113
#define IDC_BTN_DISK_OK                         1115
#define IDC_CHK_BANKADAPTION                    1116
#define IDC_CBO_BANKDEVICE                      1117
#define IDC_LBL_BANKDEVICE                      1118
